site_name: Calculation
#theme:
#  name: "material"
theme: readthedocs
nav:
  - index.md
  - tutorials.md
  - How-To Guides: how-to-guides.md
  - reference.md
  - explanation.md

plugins:
  - mkdocstrings
handlers:
    python:
      setup_commands:
        - import sys
        - sys.path.insert(0, "..")

