site_name: Calculation
#theme:
#  name: "material"
theme:
  readthedocs:
  name: material  #主题
  logo: 'images/brain.png'   # 网页左上角的logo标志

nav:
  - index.md
  - tutorials.md
  - How-To Guides: how-to-guides.md
  - reference.md
  - explanation.md

plugins:
  - mkdocstrings
handlers:
    python:
      setup_commands:
        - import sys
        - sys.path.insert(0, "..")

